### ISSUE TITLE
Is it possible to consider adding display widgets non-dongle mode

### ISSUE THREAD

**Issue by tokyo2006** [englmaxi/zmk-config#3]
Hi, I've been using your excellent display widgets! But if I am not in dongle mode, the power displayed on the left-hand does not include the battery capacity of the main hand, is it possible to consider adding compatible non-secret dog mode?
![IMG_3433](https://github.com/englmaxi/zmk-config/assets/926759/92b02443-d13b-494d-a137-4ee36d3d39eb)

**Comment by englmaxi** [comment]
I hadn't thought about it because I've seen very few boards with 128x64 displays. But I will think about the best way to implement it in the next few days. :)

**Comment by tokyo2006** [comment]
> I hadn't thought about it because I've seen very few boards with 128x64 displays. But I will think about the best way to implement it in the next few days. :)

huge thanks 👍

**Comment by englmaxi** [comment]
I added a new configuration option to also display the battery of the central device:

```ini
CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
```

Could you try it out?
(The shield moved to its own repository, if you haven't seen that: [`zmk-dongle-display`](https://github.com/englmaxi/zmk-dongle-display))

**Comment by tokyo2006** [comment]
> I added a new configuration option to also display the battery of the central device:
> 
> ```ini
> CONFIG_ZMK_DONGLE_DISPLAY_DONGLE_BATTERY=y
> ```
> 
> Could you try it out? (The shield moved to its own repository, if you haven't seen that: [`zmk-dongle-display`](https://github.com/englmaxi/zmk-dongle-display))

I've been very busy lately. I'll try it when I have rest time. Thank you again for your work!!! May the force be with you :)

**Comment by tokyo2006** [comment]
It works, but I broken my controller, I need to solder new PCB for right handle :(
